version: '3'
services:
  api:
    build: .
    command: npm run start
    image: '985122549210.dkr.ecr.eu-west-2.amazonaws.com/ec2-test:latest'
    env_file:
      - .env
    ports:
      - 3000:3000
