version: '3'
services:
  web:
    build: .
    image: 'sepa-prototype:latest'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
